### ISSUE TITLE
Choosing your Profile - Licentia still set to Female player

### ISSUE THREAD

**Issue by NeroNightfire** [cacophony-wj/LeS#17]
**Describe the bug**
Following directions of Choosing your Profile, Licentia sexual interaction places the PC in female roles. Even when set in MCM for hetrosexual, and I am a Male player, sexual interactions are generating female PC based 

**What you were doing when the bug happened**
1. Selected Licentia and self created Male Player. Finally get to a town to interact and attempt to pickup various female NPCs using the dialog menu
2. When selecting (either Charmed or Paid for) sexual interactions, any interactions evoke a PC Female role for myself no matter how the MCM SL elements are set. 
Example "Make love to me" and the NPC puts on a strap on and assumes the Male role. 
               "Sex standing up" and select nearby bed NPC will then bend forward and I will proceed to "eat her to orgasm" no actual Hetrosex.  ETC.

3. I rereviewed the directions and see Servitium "is intended for submissive females" I am understand for the PC. While I wanted to use this kinkier element, I didn't want to be the target for everyone. 

**Is the bug repeatable**
I ran to Whiterun and tested it again, When by the tall bandit structure to the East of Whiterun and have to pay a toll (sex) I am 'rubbing' inside of my cock like I have a pussy instead as I am riding ontop of the female bandit. 
Proceed into the city and both bars tried again. Using I want you to ride me (thinking cowgirl!), Love Making, and other choices PC is placed in female role, NPC will put on strap on, I will then be set (for example) jerking off the strap on, getting pegged, etc. As though I am female. Even setting the second person from Male 2 to Female 1 in the menu will not change the encounter interactions. 

**Expected behavior**
I checked all the folders, and this website, I don't see any 'setup' or other items I should have done to correct this. While I can "key" to "switch" PC for NPC, this is just a PIA for every time I want to fuck, but also limits me (from what I see) from other choice interactions (i.e. ride me isn't cowgirl)???

Appreciate the help !

**Comment by cacophony-wj** [comment]
I'll check into this. Maybe some SexLab settings from Servitium filtered over to Licentia somehow. Thanks for the heads up.

**Comment by cacophony-wj** [comment]
I am not experiencing this issue. Please confirm that you followed all of the MCM settings in the readme, particularly the section about importing settings for SexLab. If you had, strapons would be disabled by default and animations would be filtered by gender. If you still experience the issue, start a new test game and follow all of the MCM instructions exactly. Read every word in the readme and do as it says. Then save your game, talk to the Mara statue and ask to be placed in an inn, and test a scene via dialog. Not all of the animations are properly tagged, so they will not always make sense given the dialog options selected. Best to think in general categories because I am not going to manually tag 90 animations.

**Comment by cacophony-wj** [comment]
Closed due to lack of response.
